baseURL: "https://focusbitapp.com/"
languageCode: "en-us"
title: "GTD application with pomodoro timer and TODO planner"
enableRobotsTXT: true
params:
  description: "GTD application with pomodoro timer and TODO planner"
  google_universal_analytics: UA-10412407-13
  google_universal_analytics_cookiedomain: auto

