baseURL: "https://focusbitapp.com/"
languageCode: "en-us"
title: "FocusBit"
params:
  description: "Personal productvity tool"
  google_universal_analytics: UA-10412407-13
  google_universal_analytics_cookiedomain: auto

